/*
Deployment script for deltatimeMS

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "deltatimeMS"
:setvar DefaultFilePrefix "deltatimeMS"
:setvar DefaultDataPath "E:\MSSQL.MSSQLSERVER\DATA\"
:setvar DefaultLogPath "D:\MSSQL.MSSQLSERVER\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to ProjectID';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Project_Manager] (SqlSimpleColumn) will not be renamed to project_manager';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Project_Name] (SqlSimpleColumn) will not be renamed to project_name';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[Project]...';


GO
CREATE TABLE [dbo].[Project] (
    [ProjectID]       INT           NOT NULL,
    [project_name]    NVARCHAR (50) NULL,
    [project_manager] NVARCHAR (50) NULL,
    [div_code]        INT           NULL,
    [project_loc]     NVARCHAR (50) NULL,
    [overall_budget]  INT           NULL,
    [current_charges] INT           NULL,
    PRIMARY KEY CLUSTERED ([ProjectID] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
